# Generated by Django 4.2.16 on 2024-11-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_cardealer_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardealer",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.location",
            ),
        ),
    ]
